ALTER TABLE chats ADD COLUMN IF NOT EXISTS session_id VARCHAR(32);
CREATE UNIQUE INDEX IF NOT EXISTS uq_chats_session_id ON chats(session_id);
ALTER TABLE chats ADD COLUMN IF NOT EXISTS status VARCHAR(16) NOT NULL DEFAULT 'ended';
ALTER TABLE chats ADD COLUMN IF NOT EXISTS ended_by BIGINT;
ALTER TABLE chats ADD COLUMN IF NOT EXISTS end_reason VARCHAR(32);
ALTER TABLE chats ADD COLUMN IF NOT EXISTS last_activity_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS ix_chats_status ON chats(status);
